name: Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Test build
        run: |
          go build -race -v cmd/planet-exporter/main.go
          go build -race -v cmd/planet-federator/main.go

      - name: Unit tests
        run: go test -race -v ./...

  golangci-lint:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.github_token }}
          level: 'warning'
          reporter: github-pr-review
          go_version: '1.26'
